### ISSUE TITLE
App Crashes When Creating A New Note

### ISSUE THREAD

**Issue by Aesew** [alialbaali/Noto#2]
It only crashes in 1.3.1. In 1.3.0 everything works fine.
I tested it in two devices installed linageos 14.1.

Also i liked your app, i will use it after this crash at latest version gets fixed. And a import button will be really useful.

**Comment by uli-on** [comment]
androi
confirm and enlarge upon the symptoms: the crashes happen also on opening existing content. When Nunito is selected as font, Noto crashes on tapping a library. When Monospace is selected, I can open the library and even see the Monospace font although the error messages I caught with Scoop (error log catcher app) speaks of a missing resource.

-------

FATAL EXCEPTION: main
Process: com.noto, PID: 13726
android.content.res.Resources$NotFoundException: Font resource ID #0x7f090001 could not be retrieved.
	at b0.e.c(:4)
	at b0.e.b()
	at h2.a.n()
	at s3.i.u(:22)
	at s3.i.e()
	at e2.d.p(:9)
	at e2.d.f()
	at androidx.recyclerview.widget.RecyclerView$s.k(:9)
	at androidx.recyclerview.widget.RecyclerView$s.l(:72)
	at androidx.recyclerview.widget.RecyclerView$s.e(:1)
	at androidx.recyclerview.widget.LinearLayoutManager$c.c(:2)
	at androidx.recyclerview.widget.LinearLayoutManager.j1()
	at androidx.recyclerview.widget.LinearLayoutManager.W0(:2)
	at androidx.recyclerview.widget.LinearLayoutManager.p0(:17)
	at androidx.recyclerview.widget.RecyclerView.s(:2)
	at androidx.recyclerview.widget.RecyclerView.q(:7)
	at androidx.recyclerview.widget.RecyclerView.onLayout(:2)
	at android.view.View.layout(View.java:16651)
	at android.view.ViewGroup.layout(ViewGroup.java:5440)
	at j2.d.t(:6)
	at j2.e.h()
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(:4)
	at android.view.View.layout(View.java:16651)
	at android.view.ViewGroup.layout(ViewGroup.java:5440)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16651)
	at android.view.ViewGroup.layout(ViewGroup.java:5440)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16651)
	at android.view.ViewGroup.layout(ViewGroup.java:5440)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.s(:15)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(:4)
	at android.view.View.layout(View.java:16651)
	at android.view.ViewGroup.layout(ViewGroup.java:5440)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16651)
	at android.view.ViewGroup.layout(ViewGroup.java:5440)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16651)
	at android.view.ViewGroup.layout(ViewGroup.java:5440)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16651)
	at android.view.ViewGroup.layout(ViewGroup.java:5440)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16651)
	at android.view.ViewGroup.layout(ViewGroup.java:5440)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
	at android.view.View.layout(View.java:16651)
	at android.view.ViewGroup.layout(ViewGroup.java:5440)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2183)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1943)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1119)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6060)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:606)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.androi

----------

It only looks like I didn't copy to the very bottom but this is also what Scoop displays there.

**Comment by alialbaali** [comment]
Thank you so much for reporting the issue and the stack trace, very much appreciated.

I'll try to fix it in the next release!

**Comment by uli-on** [comment]
Ah, yes, I forgot to mention, it's a stock Motorola 6.0.1, Moto G4, Webview is 92.0.4515.159

**Comment by alialbaali** [comment]
Could you try selecting Nunito font, restart the app and then see if it works?

**Comment by uli-on** [comment]
The bahaviour stays the same, like described above, except for an additional crash happening while pressing android's back button in order to leave Noto. But that just for completeness, it's not reproducible.

**Comment by alialbaali** [comment]
Did the app work fine in the previous version (1.3.0)?

**Comment by uli-on** [comment]
Yes, like the OP reported.

**Comment by alialbaali** [comment]
So far I think these are two separate issues. As OP reported, it happens only when creating new note.

You shared one stack trace, could you share another one for the second crash.

Maybe I can understand where the issue is happening exactly.

**Comment by Aesew** [comment]
Caught these errors with scoop app:
FATAL EXCEPTION: main
Process: com.noto, PID: 13149
android.content.res.Resources$NotFoundException: Font resource ID #0x7f090001 could not be retrieved.
	at b0.e.c(:4)
	at b0.e.b()
	at com.noto.app.note.NoteFragment$setupState$1.j(:24)
	at com.noto.app.note.NoteFragment$setupState$1.o(:2)
	at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.a()
	at kotlinx.coroutines.flow.StateFlowImpl.b(:14)
	at x6.h.b()
	at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1.b()
	at kotlinx.coroutines.flow.FlowKt__CollectKt$launchIn$1.j(:1)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.w(:2)
	at z6.g.a(:2)
	at w6.j.r(:1)
	at u6.a.p0(:6)
	at o6.a.z(:4)
	at w6.j.l(:1)
	at com.noto.app.note.NoteFragment.E(:9)
	at androidx.fragment.app.Fragment.P()
	at androidx.fragment.app.r.f(:2)
	at androidx.fragment.app.r.k(:8)
	at androidx.fragment.app.p.E(:8)
	at androidx.fragment.app.p.Y()
	at androidx.fragment.app.p.C(:4)
	at androidx.fragment.app.p$g.run()
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6186)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by uli-on** [comment]
Hm, Scoop shows me two crashes for 1 crash I perceived. I've no diff tool on mobile, so I post them both, in sepatate messages.

Ok, then, the next 2 are for the crash when Monospace is selected and I try opening a message
-------
FATAL EXCEPTION: main
Process: com.noto, PID: 6854
android.content.res.Resources$NotFoundException: Font resource ID #0x7f090001 could not be retrieved.
	at b0.e.c(:4)
	at b0.e.b()
	at com.noto.app.note.NoteFragment$setupState$1.j(:24)
	at com.noto.app.note.NoteFragment$setupState$1.o(:2)
	at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.a()
	at kotlinx.coroutines.flow.StateFlowImpl.b(:14)
	at x6.h.b()
	at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1.b()
	at kotlinx.coroutines.flow.FlowKt__CollectKt$launchIn$1.j(:1)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.w(:2)
	at z6.g.a(:2)
	at w6.j.r(:1)
	at u6.a.p0(:6)
	at o6.a.z(:4)
	at w6.j.l(:1)
	at com.noto.app.note.NoteFragment.E(:9)
	at androidx.fragment.app.Fragment.P()
	at androidx.fragment.app.r.f(:2)
	at androidx.fragment.app.r.k(:8)
	at androidx.fragment.app.p.E(:8)
	at androidx.fragment.app.p.Y()
	at androidx.fragment.app.p.C(:4)
	at androidx.fragment.app.p$g.run()
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by uli-on** [comment]
FATAL EXCEPTION: main
Process: com.noto, PID: 2686
android.content.res.Resources$NotFoundException: Font resource ID #0x7f090001 could not be retrieved.
	at b0.e.c(:4)
	at b0.e.b()
	at h2.a.n()
	at s3.i.u(:22)
	at s3.i.e()
	at e2.d.p(:9)
	at e2.d.f()
	at androidx.recyclerview.widget.RecyclerView$s.k(:9)
	at androidx.recyclerview.widget.RecyclerView$s.l(:72)
	at androidx.recyclerview.widget.RecyclerView$s.e(:1)
	at androidx.recyclerview.widget.LinearLayoutManager$c.c(:2)
	at androidx.recyclerview.widget.LinearLayoutManager.j1()
	at androidx.recyclerview.widget.LinearLayoutManager.W0(:2)
	at androidx.recyclerview.widget.LinearLayoutManager.p0(:17)
	at androidx.recyclerview.widget.RecyclerView.s(:2)
	at androidx.recyclerview.widget.RecyclerView.q(:7)
	at androidx.recyclerview.widget.RecyclerView.onLayout(:2)
	at android.view.View.layout(View.java:16651)
	at android.view.ViewGroup.layout(ViewGroup.java:5440)
	at j2.d.t(:6)
	at j2.e.h()
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(:4)
	at android.view.View.layout(View.java:16651)
	at android.view.ViewGroup.layout(ViewGroup.java:5440)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16651)
	at android.view.ViewGroup.layout(ViewGroup.java:5440)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16651)
	at android.view.ViewGroup.layout(ViewGroup.java:5440)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.s(:15)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(:4)
	at android.view.View.layout(View.java:16651)
	at android.view.ViewGroup.layout(ViewGroup.java:5440)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16651)
	at android.view.ViewGroup.layout(ViewGroup.java:5440)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16651)
	at android.view.ViewGroup.layout(ViewGroup.java:5440)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16651)
	at android.view.ViewGroup.layout(ViewGroup.java:5440)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16651)
	at android.view.ViewGroup.layout(ViewGroup.java:5440)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
	at android.view.View.layout(View.java:16651)
	at android.view.ViewGroup.layout(ViewGroup.java:5440)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2183)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1943)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1119)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6060)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:606)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android

**Comment by alialbaali** [comment]
Github won't let me attach the apk to the comment, so I had to attach to the current [release](https://github.com/alialbaali/Noto/releases/tag/v1.3.1). Try downloading the debug app and let me know if any of the issues persist with and without the monospace font.

**Comment by uli-on** [comment]
And this is with Nunito selected, tapping on just the library.

-------
FATAL EXCEPTION: main
Process: com.noto, PID: 7593
android.content.res.Resources$NotFoundException: Font resource ID #0x7f090001 could not be retrieved.
	at b0.e.c(:4)
	at b0.e.b()
	at h2.a.n()
	at s3.i.u(:22)
	at s3.i.e()
	at e2.d.p(:9)
	at e2.d.f()
	at androidx.recyclerview.widget.RecyclerView$s.k(:9)
	at androidx.recyclerview.widget.RecyclerView$s.l(:72)
	at androidx.recyclerview.widget.RecyclerView$s.e(:1)
	at androidx.recyclerview.widget.LinearLayoutManager$c.c(:2)
	at androidx.recyclerview.widget.LinearLayoutManager.j1()
	at androidx.recyclerview.widget.LinearLayoutManager.W0(:2)
	at androidx.recyclerview.widget.LinearLayoutManager.p0(:17)
	at androidx.recyclerview.widget.RecyclerView.s(:2)
	at androidx.recyclerview.widget.RecyclerView.q(:7)
	at androidx.recyclerview.widget.RecyclerView.onLayout(:2)
	at android.view.View.layout(View.java:16651)
	at android.view.ViewGroup.layout(ViewGroup.java:5440)
	at j2.d.t(:6)
	at j2.e.h()
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(:4)
	at android.view.View.layout(View.java:16651)
	at android.view.ViewGroup.layout(ViewGroup.java:5440)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16651)
	at android.view.ViewGroup.layout(ViewGroup.java:5440)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16651)
	at android.view.ViewGroup.layout(ViewGroup.java:5440)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.s(:15)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(:4)
	at android.view.View.layout(View.java:16651)
	at android.view.ViewGroup.layout(ViewGroup.java:5440)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16651)
	at android.view.ViewGroup.layout(ViewGroup.java:5440)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16651)
	at android.view.ViewGroup.layout(ViewGroup.java:5440)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at android.view.View.layout(View.java:16651)
	at android.view.ViewGroup.layout(ViewGroup.java:5440)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
	at android.view.View.layout(View.java:16651)
	at android.view.ViewGroup.layout(ViewGroup.java:5440)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
	at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
	at android.view.View.layout(View.java:16651)
	at android.view.ViewGroup.layout(ViewGroup.java:5440)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2183)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1943)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1119)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6060)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
	at android.view.Choreographer.doFrame(Choreographer.java:606)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android

**Comment by uli-on** [comment]
Crashes already on library creation. I post both errors Scoop caught, can't tell though which is which crash, one happened with Nunito, one with Monospace

-----

FATAL EXCEPTION: main
Process: com.noto.debug, PID: 9624
android.content.res.Resources$NotFoundException: Resource ID #0x7f0f0001
	at android.content.res.Resources.getValue(Resources.java:1351)
	at android.content.res.Resources.getDrawable(Resources.java:804)
	at androidx.core.content.res.ResourcesCompat.getDrawable(ResourcesCompat.java:94)
	at com.noto.app.util.ResourceUtilsKt.drawableResource(ResourceUtils.kt:13)
	at com.noto.app.util.ExtensionUtilsKt.createPinnedShortcut(ExtensionUtils.kt:157)
	at com.noto.app.library.NewLibraryDialogFragment.updatePinnedShortcut(NewLibraryDialogFragment.kt:105)
	at com.noto.app.library.NewLibraryDialogFragment.setupListeners$lambda-2(NewLibraryDialogFragment.kt:71)
	at com.noto.app.library.NewLibraryDialogFragment.$r8$lambda$xNzWR14OpcYmJNebvnI9mA56aXc(NewLibraryDialogFragment.kt)
	at com.noto.app.library.NewLibraryDialogFragment$$ExternalSyntheticLambda0.onClick(Unknown Source)
	at android.view.View.performClick(View.java:5207)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
	at android.view.View$PerformClick.run(View.java:21168)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by uli-on** [comment]
FATAL EXCEPTION: main
Process: com.noto.debug, PID: 9517
android.content.res.Resources$NotFoundException: Resource ID #0x7f0f0001
	at android.content.res.Resources.getValue(Resources.java:1351)
	at android.content.res.Resources.getDrawable(Resources.java:804)
	at androidx.core.content.res.ResourcesCompat.getDrawable(ResourcesCompat.java:94)
	at com.noto.app.util.ResourceUtilsKt.drawableResource(ResourceUtils.kt:13)
	at com.noto.app.util.ExtensionUtilsKt.createPinnedShortcut(ExtensionUtils.kt:157)
	at com.noto.app.library.NewLibraryDialogFragment.updatePinnedShortcut(NewLibraryDialogFragment.kt:105)
	at com.noto.app.library.NewLibraryDialogFragment.setupListeners$lambda-2(NewLibraryDialogFragment.kt:71)
	at com.noto.app.library.NewLibraryDialogFragment.$r8$lambda$xNzWR14OpcYmJNebvnI9mA56aXc(NewLibraryDialogFragment.kt)
	at com.noto.app.library.NewLibraryDialogFragment$$ExternalSyntheticLambda0.onClick(Unknown Source)
	at android.view.View.performClick(View.java:5207)
	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1119)
	at android.view.View$PerformClick.run(View.java:21168)
	at android.os.Handler.handleCallback(Handler.java:746)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

**Comment by alialbaali** [comment]
Okay, I've uploaded [a debug apk](https://github.com/alialbaali/Noto/releases/tag/v1.3.1) again, check with this one. No need to post stack trace anymore as they're all matching and I'm close to figuring out the issue where.

**Comment by uli-on** [comment]
debug v2 also crashes on library creation, sorry.

**Comment by alialbaali** [comment]
Okay, I just read the stack trace again and the problem seems different this time. I apologize for taking so much of your time!

I've uploaded the [apk](https://github.com/alialbaali/Noto/releases/tag/v1.3.1) again, this time it should work fine with no crashes at all.

**Comment by uli-on** [comment]
Thanks for thanking, and thanks for thinking of a separate test version, I've had very different experience while getting to the bottom of things with a commercial dev.

V3 didn't crash, you were right, but there's also no Monospace font in notes. Keep a stiff upperlip ;)

**Comment by alialbaali** [comment]
I'm glad I can help!

I'm gonna ask you one more time to install the [v4](https://github.com/alialbaali/Noto/releases/tag/v1.3.1) version, so I can know if the problem is related with monospace font or not.

**Comment by uli-on** [comment]
Yup yup, Monospace is up, thanks. 
As for my part we can close the topic.

**Comment by alialbaali** [comment]
I'll apply the fix in the next release. Thank you for your time!

**Comment by uli-on** [comment]
You're welcome. (Have a nice evening, or some other nice time of day. )

**Comment by alialbaali** [comment]
You too!
