### ISSUE TITLE
App crashes if you delete a new note while in the editor

### ISSUE THREAD

**Issue by WTechNinja** [alialbaali/Noto#5]
If you start writing a new note, and then decide to delete it without leaving the editor first, the app will crash. 
I am on version 1.3.5

Steps to reproduce:
1. Make new note
2. Add some text
3. Without leaving the editor, open the little "Note options" menu on the bottom left and hit "Delete note"
4. The app should crash

If you leave the editor first and then delete the note it has no issues.

Here's a stack trace:
`FATAL EXCEPTION: main
Process: com.noto, PID: 28513
java.lang.NullPointerException: Parameter specified as non-null is null: method com.noto.app.note.NoteViewModel$createOrUpdateNote$1$1$1.h, parameter note
	at com.noto.app.note.NoteViewModel$createOrUpdateNote$1$1$1.h(:4)
	at com.noto.app.note.NoteViewModel$createOrUpdateNote$1$1$1.v(:2)
	at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.a(Unknown Source:73)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.t(:1)
	at kotlinx.coroutines.flow.internal.SafeCollector.r(:9)
	at kotlinx.coroutines.flow.internal.SafeCollector.a(Unknown Source:0)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.a(:8)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.h(:1)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.s(:2)
	at m6.f0.run(Unknown Source:86)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7050)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)`

**Comment by alialbaali** [comment]
Thank you for the report!

This issue should be fixed in the next release.

**Comment by WTechNinja** [comment]
Confirmed, it's fixed.
