### ISSUE TITLE
Bug: App crashes on launch

### ISSUE THREAD

**Issue by WTechNinja** [alialbaali/Noto#7]
I can't get the latest version (1.4.0) to launch, it just crashes. Here's the log;

`FATAL EXCEPTION: main
Process: com.noto, PID: 8852
android.database.sqlite.SQLiteException: no such column: is_set_new_note_cursor_on_title (code 1 SQLITE_ERROR[1]): , while compiling: INSERT INTO `_new_libraries` (color,note_preview_size,creation_date,is_set_new_note_cursor_on_title,title,is_show_note_creation_date,is_pinned,is_archived,sorting,sorting_order,layout_manager,id,position,sorting_method) SELECT color,note_preview_size,creation_date,is_set_new_note_cursor_on_title,title,is_show_note_creation_date,is_pinned,is_archived,sorting,sorting_order,layout_manager,id,position,sorting_method FROM `libraries`
	at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
	at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1229)
	at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:703)
	at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
	at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
	at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2227)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2155)
	at e1.a.m(Unknown Source:2)
	at f3.f.a(:6)
	at androidx.room.c.f(:3)
	at e1.b$a.onUpgrade(:2)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:400)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
	at e1.b$a.e(Unknown Source:4)
	at e1.b.E(Unknown Source:4)
	at androidx.room.RoomDatabase.h(Unknown Source:2)
	at androidx.room.RoomDatabase.b(Unknown Source:0)
	at androidx.room.RoomDatabase.m(Unknown Source:3)
	at c1.c.c(Unknown Source:1)
	at g3.b$i.call(:3)
	at androidx.room.CoroutinesRoom$Companion$createFlow$1$1$1.h(:2)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.u(:2)
	at n6.f0.run(Unknown Source:86)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
	Suppressed: android.database.sqlite.SQLiteException: no such column: is_set_new_note_cursor_on_title (code 1 SQLITE_ERROR[1]): , while compiling: INSERT INTO `_new_libraries` (color,note_preview_size,creation_date,is_set_new_note_cursor_on_title,title,is_show_note_creation_date,is_pinned,is_archived,sorting,sorting_order,layout_manager,id,position,sorting_method) SELECT color,note_preview_size,creation_date,is_set_new_note_cursor_on_title,title,is_show_note_creation_date,is_pinned,is_archived,sorting,sorting_order,layout_manager,id,position,sorting_method FROM `libraries`
		at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
		at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:1229)
		at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:703)
		at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
		at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:59)
		at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
		at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:2227)
		at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:2155)
		at e1.a.m(Unknown Source:2)
		at f3.f.a(:6)
		at androidx.room.c.f(:3)
		at e1.b$a.onUpgrade(:2)
		at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:400)
		at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:298)
		at e1.b$a.e(Unknown Source:4)
		at e1.b.E(Unknown Source:4)
		at androidx.room.RoomDatabase.h(Unknown Source:2)
		at androidx.room.RoomDatabase.b(Unknown Source:0)
		at androidx.room.RoomDatabase.m(Unknown Source:3)
		at c1.c.c(Unknown Source:1)
		at g3.b$a.call(:3)
		... 6 more`

**Comment by alialbaali** [comment]
Could you let me know from where did you download the last version?

**Comment by alialbaali** [comment]
I just released 1.4.1, check it and let me know!

**Comment by WTechNinja** [comment]
(Was busy, my apologies)
It's fixed! Thanks again!
